swagger: '2.0'
info:
  title: AnprServiceN000
  description: ''
  x-ibm-name: anprservicen000
  version: 1.0.0
schemes:
  - https
basePath: /AnprServiceN000
produces:
  - application/xml
consumes:
  - text/xml
securityDefinitions:
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
    description: ''
security:
  - clientID: []
x-ibm-configuration:
  type: wsdl
  wsdl-definition:
    wsdl: wsdlN000/N000serviziNotifiche.wsdl
    service: AnprServiceN000
    port: AnprServicePortN000
    soap-version: '1.1'
  assembly:
    execute:
      - proxy:
          title: proxy
          target-url: ''
  gateway: datapower-gateway
  enforced: true
  testable: true
  phase: realized
  cors:
    enabled: true
paths:
  /inoltroNotificaANPR:
    post:
      summary: Operation inoltroNotificaANPR
      description: ''
      operationId: inoltroNotificaANPR
      x-ibm-soap:
        soap-action: ''
        soap-operation: '{http://sogei.it/ANPR/N000AnprService}RichiestaN000'
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/inoltroNotificaANPRInput'
      responses:
        default:
          description: ''
          schema:
            $ref: '#/definitions/inoltroNotificaANPROutput'
definitions:
  Security:
    xml:
      namespace: >-
        http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
      prefix: wsse
    type: object
    properties:
      UsernameToken:
        xml:
          namespace: >-
            http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
          prefix: wsse
        type: object
        properties:
          Username:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
              prefix: wsse
            type: string
          Password:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
              prefix: wsse
            type: string
          Nonce:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd
              prefix: wsse
            type: string
            properties:
              EncodingType:
                xml:
                  namespace: ''
                  attribute: true
                type: string
          Created:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
            type: string
      Timestamp:
        xml:
          namespace: >-
            http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
          prefix: wsu
        type: object
        properties:
          Created:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
            type: string
          Expires:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
            type: string
          Id:
            xml:
              namespace: >-
                http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd
              prefix: wsu
              attribute: true
            type: string
  inoltroNotificaANPRInput:
    type: object
    properties:
      Envelope:
        xml:
          prefix: soapenv
          namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
        type: object
        properties:
          Header:
            $ref: '#/definitions/inoltroNotificaANPRHeader'
          Body:
            type: object
            properties:
              RichiestaN000:
                $ref: '#/definitions/RichiestaN000_tns'
            required:
              - RichiestaN000
        required:
          - Body
    required:
      - Envelope
    example: >-

      <soapenv:Envelope
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
       <soapenv:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <wsse:UsernameToken>
          <wsse:Username>string</wsse:Username>
          <wsse:Password>string</wsse:Password>
          <wsse:Nonce EncodingType="string">string</wsse:Nonce>
          <wsu:Created>string</wsu:Created>
         </wsse:UsernameToken>
         <wsu:Timestamp wsu:Id="string">
          <wsu:Created>string</wsu:Created>
          <wsu:Expires>string</wsu:Expires>
         </wsu:Timestamp>
        </wsse:Security>
       </soapenv:Header>
       <soapenv:Body>
        <tns:RichiestaN000 xmlns:tns="http://sogei.it/ANPR/N000AnprService"><!-- mandatory -->
         <testataNotifica><!-- mandatory -->
          <tipoNotifica><!-- mandatory -->string</tipoNotifica>
          <codMittente><!-- mandatory -->string</codMittente>
          <codDestinatario><!-- mandatory -->string</codDestinatario>
          <dataOraRichiesta><!-- mandatory -->2016-04-18T14:07:37</dataOraRichiesta>
          <idOperazioneANPR><!-- mandatory -->3</idOperazioneANPR>
         </testataNotifica>
         <contenuto><!-- mandatory -->abcd</contenuto>
        </tns:RichiestaN000>
       </soapenv:Body>
      </soapenv:Envelope>
  inoltroNotificaANPRHeader:
    type: object
    properties:
      Security:
        $ref: '#/definitions/Security'
  inoltroNotificaANPROutput:
    type: object
    properties:
      Envelope:
        xml:
          prefix: soapenv
          namespace: 'http://schemas.xmlsoap.org/soap/envelope/'
        type: object
        properties:
          Body:
            type: object
            properties:
              RispostaN000:
                $ref: '#/definitions/RispostaN000_tns'
        required:
          - Body
    required:
      - Envelope
    example: >-

      <soapenv:Envelope
      xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
       <soapenv:Body>
        <tns:RispostaN000 xmlns:tns="http://sogei.it/ANPR/N000AnprService">
         <codiceEsito><!-- mandatory -->string</codiceEsito>
         <esito><!-- mandatory -->string</esito>
        </tns:RispostaN000>
       </soapenv:Body>
      </soapenv:Envelope>
  RichiestaN000_tns:
    xml:
      namespace: 'http://sogei.it/ANPR/N000AnprService'
      prefix: tns
    type: object
    properties:
      testataNotifica:
        $ref: '#/definitions/tipoDatoTestataNotifica_tns'
      contenuto:
        type: string
        format: binary
        xml:
          namespace: ''
          prefix: ''
    required:
      - testataNotifica
      - contenuto
    example: |-

      <tns:RichiestaN000 xmlns:tns="http://sogei.it/ANPR/N000AnprService">
       <testataNotifica><!-- mandatory -->
        <tipoNotifica><!-- mandatory -->string</tipoNotifica>
        <codMittente><!-- mandatory -->string</codMittente>
        <codDestinatario><!-- mandatory -->string</codDestinatario>
        <dataOraRichiesta><!-- mandatory -->2016-04-18T14:07:37</dataOraRichiesta>
        <idOperazioneANPR><!-- mandatory -->3</idOperazioneANPR>
       </testataNotifica>
       <contenuto><!-- mandatory -->abcd</contenuto>
      </tns:RichiestaN000>
  RispostaN000_tns:
    xml:
      namespace: 'http://sogei.it/ANPR/N000AnprService'
      prefix: tns
    type: object
    properties:
      codiceEsito:
        type: string
        xml:
          namespace: ''
          prefix: ''
      esito:
        type: string
        xml:
          namespace: ''
          prefix: ''
    required:
      - codiceEsito
      - esito
    example: |-

      <tns:RispostaN000 xmlns:tns="http://sogei.it/ANPR/N000AnprService">
       <codiceEsito><!-- mandatory -->string</codiceEsito>
       <esito><!-- mandatory -->string</esito>
      </tns:RispostaN000>
  tipoDatoTestataNotifica_tns:
    xml:
      namespace: ''
      prefix: ''
    type: object
    properties:
      tipoNotifica:
        type: string
        xml:
          namespace: ''
          prefix: ''
      codMittente:
        type: string
        xml:
          namespace: ''
          prefix: ''
      codDestinatario:
        type: string
        xml:
          namespace: ''
          prefix: ''
      dataOraRichiesta:
        type: string
        format: date-time
        xml:
          namespace: ''
          prefix: ''
      idOperazioneANPR:
        type: number
        xml:
          namespace: ''
          prefix: ''
    required:
      - tipoNotifica
      - codMittente
      - codDestinatario
      - dataOraRichiesta
      - idOperazioneANPR
    x-xsi-type: tipoDatoTestataNotifica
    x-xsi-type-xml:
      namespace: 'http://sogei.it/ANPR/N000AnprService'
      prefix: tns
    x-xsi-type-uniquename: tipoDatoTestataNotifica_tns
